Energy renormalization
kymatio/kymatio pull request #765
Opened 2021-07-25 21:49 UTC by OverLordGoldDragon

LP sum peaks at 2 for `Scattering1D`; especially helpful for JTFS where deviations from tight frame amplify quintically. See [discussion](https://github.com/kymatio/kymatio/discussions/732#discussioncomment-855703).

Some code is in place for JTFS. This branch rests on and can merge after #673.

2021-10-10 16:12 UTC, lostanlen commented
i am confused as to how this code interacts with the rest of the library. what problem are you solving? who will use these new functions?

2021-10-10 16:59 UTC, OverLordGoldDragon commented
> what problem are you solving?

Energy conservation - (constant) rescaling filters such that LP sum is as close to a tight frame as possible, as [here](https://github.com/kymatio/kymatio/discussions/732#discussioncomment-986435).

> explanation of `deviations from tight frame amplify quintically`

[`|psi_t|^2 * |psi_f|^2`](https://github.com/kymatio/kymatio/discussions/732#discussioncomment-855703) -- if they're all e.g. `0.9`, that's `0.9^4 = 0.6561`, so effects of deviating from LP sum of `1` are more dramatic for JTFS.

2021-10-10 17:01 UTC, lostanlen commented
ah, yes i see what you mean. The more cascaded filterbanks, the more sensitive to these deviations

when i saw the title "energy renormalization" i thought that it was a stage of the transformation. But really you're talking about a renormalization step that can be included in the filterbank design and thus comes at no additional cost at transform time. Am i right?

2021-10-10 17:07 UTC, OverLordGoldDragon commented
That's right, it's part of `create_filters()`, if `'energy'` is in `normalize`, so old behavior is accessed via `normalize='l1'`.

2021-10-10 17:21 UTC, lostanlen commented
Looks great. I though `energy-l1` was the default!

2022-04-27 00:28 UTC, MuawizChaudhary requested changes
@OverLordGoldDragon Can you do a review and comment which functions specifcally are for JTFS?

2022-05-31 16:55 UTC, MuawizChaudhary commented
[energy renormalization](https://www.youtube.com/watch?v=umDr0mPuyQc&ab_channel=RetroPep), we hardly knew thee

2022-05-31 16:56 UTC, MuawizChaudhary commented
[energy renormalization](https://www.youtube.com/watch?v=umDr0mPuyQc&ab_channel=RetroPep), we hardly knew thee

2022-05-31 16:56 UTC, closed without merging