DOC Use tight_layout to prevent plot axes from overlapping one another
kymatio/kymatio pull request #827
Opened 2022-06-02 02:24 UTC by MuawizChaudhary

This PR fixes plots in the 1d code from overlapping one another. 

From `plot_real_signal.py`.
![Figure_2](https://user-images.githubusercontent.com/39755015/171536172-229fd2fb-c79d-4946-8000-a54e0dfe9e7e.png)
![Figure_2_fixed](https://user-images.githubusercontent.com/39755015/171536179-57376d6d-d4ac-4cc4-8084-1a06bf4253b6.png)

From `plot_synthetic.py`.
![Figure_3](https://user-images.githubusercontent.com/39755015/171536181-e555b49b-357f-4390-b732-b8b2625e86b9.png)
![Figure_3_fixed](https://user-images.githubusercontent.com/39755015/171536183-8a0d3ec7-56f3-42ec-9e47-3baa3b48c888.png)

This goes a small way of solving #817

2022-06-02 08:20 UTC, lostanlen approved these changes
well done @MuawizChaudhary

2022-06-10 11:24 UTC, janden requested changes

2022-06-10 11:24 UTC, janden commented on examples/1d/plot_real_signal.py
> +plt.tight_layout()
Could you move this to just above `plt.show()` (as you did for `plot_synthetic`)?

2022-06-11 01:57 UTC, MuawizChaudhary commented
@janden lemme know if its all good

2022-06-13 21:45 UTC, janden approved these changes

2022-06-14 00:26 UTC, merged